name: Windows CI (testing)
on:
  push:
    branches: [ "testing/**", "testing", "testing-v*" ]
  pull_request:
    branches: [ "testing/**", "testing", "testing-v*" ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          New-Item -ItemType Directory -Force -Path build\logs | Out-Null
      - name: Run tests (headless)
        env:
          QT_QPA_PLATFORM: offscreen
          PYTHONPATH: .
        shell: pwsh
        run: |
          pytest -q 2>&1 | Tee-Object -FilePath build\logs\pytest.log
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: build/logs/pytest.log
